language: node_js
node_js:
  - 12.16.2
script:
  - npm run test
after_script:
  - cat ./coverage/lcov.info | coveralls
deploy:
  provider: heroku
  api_key:
    secure: rk5FqGIRu3eWc3DSwUbMzHExB6QJpl9++Tq5Bn2bjymrWlAhjfSp3auX0aUIdlP8/nMiuF1Fmjlc0Yp37Sb9OpgrII7kZvJHn+UoOMtnUEmHZc2dSJyK3jo0IPGFSJ/AlifgzppEho4KnaAK7GsjMBWe4nJi2NZZUZ+yFBeYVWMElooShmRlhRPXEaj+BtlVrdiKgg9ifv29vrjXNXoiFsoWsh/hLvPg9/eqAdbfCCsqVefj2YjjKwUMgv6vrUlgHTqLTPG9B9ax2yYUdKmzeSK5GGqjZi8Hmd8ZLAqSBvGEc0A3pNVblYoV+nUO1+qFqATjIPfD5uLCYLRLDwLVvVITnBHgmDdiDaAqP93JDthKIqgam4s8BP/+tJ+IgHySGUak33NIz/TprjyYbCa0eF4pDODtf441+sWROEBbZO99cTBKRbWUHjZogrGtn0ACHt4hoqNB3IByFxwV5FJ8mJhBoFHUs91f4C+eDVIbTpEZhHZRNWjQMdr9Fi+k3hM36Dxnkx5tnQY7OUbCCLU8C+mRaTxyKJ8Ix13rdE6fuF4Yc1L4Xa1vwu9vNR3AUXWQQtQvOHPQJyQPaoTS6IuWA1iaLwt4mFzcV1o2hst6w7DmOJjoAduRWGF4N7oPTy2YAdRgUQdxQ9SP3/67pD+NYXiXlZWq69vQE0LjKrz4X38=
    app:
      develop: cod19-gp-dev
      master: cod19-gp
notifications:
  email: false
